make the reports folder
UBC-MDS/DSCI-532_2024_4_crime-tracker pull request #8
Opened 2024-03-25 23:15 UTC by MoNorouzi23

Please review and merge it!

2024-03-26 07:11 UTC, 786213750 approved these changes
Looks great!

2024-03-26 16:35 UTC, s-voon commented on CODE_OF_CONDUCT.md
> +Every member of our community has the right to have their identity respected. DSCI 522 Group 17 is dedicated to providing a positive experience for everyone, regardless of age, gender identity and ex
DSCI 532 Group 4 instead of DSCI 522 Group 17

2024-03-26 16:35 UTC, s-voon commented on CODE_OF_CONDUCT.md
> +All participants in our events and communications are expected to show respect and courtesy to others. All interactions should be professional regardless of platform: either online or in-person. In o
Group 4

2024-03-26 16:39 UTC, s-voon commented on CODE_OF_CONDUCT.md
> +Every member of our community has the right to have their identity respected. DSCI 522 Group 17 is dedicated to providing a positive experience for everyone, regardless of age, gender identity and ex
```suggestion
Every member of our community has the right to have their identity respected. DSCI 532 Group 4 is dedicated to providing a positive experience for everyone, regardless of age, gender identity and expression, sexual orientation, disability, physical appearance, body size, ethnicity, nationality, race, or religion (or lack thereof), education, or socio-economic status.
```

2024-03-26 16:39 UTC, s-voon commented on CODE_OF_CONDUCT.md
> +All participants in our events and communications are expected to show respect and courtesy to others. All interactions should be professional regardless of platform: either online or in-person. In o
```suggestion
All participants in our events and communications are expected to show respect and courtesy to others. All interactions should be professional regardless of platform: either online or in-person. In order to foster a positive and professional learning environment we encourage the following kinds of behaviours in all Group 4 events and platforms:
```

2024-03-26 16:40 UTC, s-voon commented on CODE_OF_CONDUCT.md
> +Participants who are asked to stop any inappropriate behavior are expected to comply immediately. This applies to any Group 17 meetings and platforms, either online or in-person. If a participant eng
```suggestion
Participants who are asked to stop any inappropriate behavior are expected to comply immediately. This applies to any Group 4 meetings and platforms, either online or in-person. If a participant engages in behavior that violates this code of conduct, the team may warn the offender and or engage the DSCI 532 instructor to investigate the Code of Conduct violation and impose appropriate sanctions.
```

2024-03-26 16:41 UTC, s-voon commented on CODE_OF_CONDUCT.md
> +If someone violates the Code of Conduct during a Group 17 event or in an online space outside of organised events, we ask that you ask the person to stop. If they do not stop the inappropriate behavi
```suggestion
If someone violates the Code of Conduct during a Group 4 event or in an online space outside of organised events, we ask that you ask the person to stop. If they do not stop the inappropriate behavior immediately, raise the issue with the team and the behavior will be addressed by the rest of the team members. If you do not feel the behavior has been adequately addressed, or it has still not stopped, report it to the Instructor(s). The current instructor(s) of DSCI 532 is(are) Joel Ostblom. An email message to the email address listed in the course syllabus will be seen by the instructor. To report a DSCI 532 Group 4 code of conduct violation that will not be seen by your instructor, an alternative contact person is Milad Maymay, Director, Program Operations and Student Management, MDS Vancouver. His email is maymay@science.ubc.ca.
```

2024-03-26 16:42 UTC, s-voon requested changes
Make a few changes, specifically on the code of conduct.md file. Please review it! Thanks!

2024-03-26 17:06 UTC, WaleedMahmood1 commented
Thanks for the review @s-voon! I have accepted and committed your review into the `CODE_OF_CONDUCT.md` file.

2024-03-26 17:09 UTC, WaleedMahmood1 approved these changes
Project structure looks complete now, I believe. We can merge this pull request with main now.

2024-03-26 17:12 UTC, WaleedMahmood1 approved these changes
Thanks for the review, I have committed these changes!

2024-03-26 17:13 UTC, WaleedMahmood1 approved these changes

2024-03-27 02:41 UTC, s-voon approved these changes

2024-03-27 02:41 UTC, merged